#
###################################
# Site wide configuration
####################################
#
title: MattOuille.com
email: matthew.ouille@gmail.com
description: Tutorials, OpEds, and Musings by Matt Ouille
url: https://mattouille.com # the base hostname & protocol for your site
keywords: ["Python", "Linux", "DevOps", "SRE", "Site Reliability Engineering", "Automation"]
future: false

#
###################################
# Jekyll configuration
####################################
#
timezone:           America/Chicago
markdown:           kramdown
highlighter:        rouge
excerpt_separator:  <!--more-->
permalink:          /articles/:year-:month/:title
paginate:           5
paginate_path:      /page:num/
page:
  comments: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Matt Ouille
  avatar: profile.jpg
  job: "Site Reliability Engineer"
  bio: "A software engineer focused on infrastructure automation, Linux, and service reliability."
  email: matthew.ouille@gmail.com
  disqus-shortname: mattouille
  twitter: codencombovers #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-49694865-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mattouille #username
  stackoverflow: 5854293/matt-o
  linkedin: mattouille #username
  xing: #username
  instagram: code_n_combovers #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
